<a href="https://colab.research.google.com/github/Shreyaprashanth/Samsung__Innovation__Campus/blob/main/PCA_Wine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.datasets import load_wine



In [ ]:
df= load_wine()

In [ ]:
X = wine.data
y = wine.target

In [ ]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [ ]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler=StandardScaler()


In [ ]:
X_scaled = scaler.fit_transform(X)

In [ ]:
X_scaled

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.52437837,
        -1.42894777, -0.59516041]])

In [ ]:
pca_wine = PCA()
pca_wine.fit(X_scaled)

PCA()

In [ ]:
exp_variance_X=pca_wine.explained_variance_ratio_

In [ ]:
exp_variance_X

array([0.36198848, 0.1920749 , 0.11123631, 0.0706903 , 0.06563294,
       0.04935823, 0.04238679, 0.02680749, 0.02222153, 0.01930019,
       0.01736836, 0.01298233, 0.00795215])

In [ ]:
import pandas as pd


In [ ]:
components_X = pd.DataFrame(pca_wine.components_,columns=df.feature_names)

In [ ]:
components_X

alcohol  malic_acid       ash  alcalinity_of_ash  magnesium  \
0   0.144329   -0.245188 -0.002051          -0.239320   0.141992   
1   0.483652    0.224931  0.316069          -0.010591   0.299634   
2  -0.207383    0.089013  0.626224           0.612080   0.130757   
3  -0.017856    0.536890 -0.214176           0.060859  -0.351797   
4  -0.265664    0.035214 -0.143025           0.066103   0.727049   
5   0.213539    0.536814  0.154475          -0.100825   0.038144   
6  -0.056396    0.420524 -0.149171          -0.286969   0.322883   
7   0.396139    0.065827 -0.170260           0.427970  -0.156361   
8  -0.508619    0.075283  0.307694          -0.200449  -0.271403   
9   0.211605   -0.309080 -0.027125           0.052799   0.067870   
10 -0.225917    0.076486 -0.498691           0.479314   0.071289   
11 -0.266286    0.121696 -0.049622          -0.055743   0.062220   
12  0.014970    0.025964 -0.141218           0.091683   0.056774   

    total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
0        0.394661    0.422934             -0.298533         0.313429   
1        0.065040   -0.003360              0.028779         0.039302   
2        0.146179    0.150682              0.170368         0.149454   
3        0.198068    0.152295             -0.203301         0.399057   
4       -0.149318   -0.109026             -0.500703         0.136860   
5       -0.084122   -0.018920             -0.258594        -0.533795   
6       -0.027925   -0.060685              0.595447         0.372139   
7       -0.405934   -0.187245             -0.233285         0.368227   
8       -0.286035   -0.049578             -0.195501         0.209145   
9       -0.320131   -0.163151              0.215535         0.134184   
10       0.304341   -0.025694              0.116896        -0.237363   
11      -0.303882   -0.042899              0.042352        -0.095553   
12      -0.463908    0.832257              0.114040        -0.116917   

    color_intensity       hue  od280/od315_of_diluted_wines   proline  
0         -0.088617  0.296715                      0.376167  0.286752  
1          0.529996 -0.279235                     -0.164496  0.364903  
2         -0.137306  0.085222                      0.166005 -0.126746  
3          0.065926 -0.427771                      0.184121 -0.232071  
4         -0.076437 -0.173615                     -0.101161 -0.157869  
5         -0.418644  0.105983                      0.265851  0.119726  
6         -0.227712  0.232076                     -0.044764  0.076805  
7         -0.033797  0.436624                     -0.078108  0.120023  
8         -0.056218 -0.085828                     -0.137227  0.575786  
9         -0.290775 -0.522399                      0.523706  0.162116  
10         0.031839 -0.048212                      0.046423  0.539270  
11         0.604222  0.259214                      0.600959 -0.079402  
12        -0.011993 -0.089889                     -0.156718  0.014447

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier()

In [ ]:
rf_classifier.fit(X, y)

RandomForestClassifier()

In [ ]:
rf_classifier.feature_importances_

array([0.11538278, 0.03252148, 0.01320899, 0.02410598, 0.03612422,
       0.06395141, 0.16114366, 0.01123333, 0.02196585, 0.16215263,
       0.07709884, 0.10255348, 0.17855734])

In [ ]:
importances_wine =rf_classifier.feature_importances_

In [ ]:
feature_importance_wine_df = pd.DataFrame({
    'Feature': df.feature_names,
    'Importance': importances_wine
}).sort_values(by='Importance', ascending=False)

In [ ]:
feature_importance_wine_df

Feature  Importance
12                       proline    0.178557
9                color_intensity    0.162153
6                     flavanoids    0.161144
0                        alcohol    0.115383
11  od280/od315_of_diluted_wines    0.102553
10                           hue    0.077099
5                  total_phenols    0.063951
4                      magnesium    0.036124
1                     malic_acid    0.032521
3              alcalinity_of_ash    0.024106
8                proanthocyanins    0.021966
2                            ash    0.013209
7           nonflavanoid_phenols    0.011233